openapi4j/openapi4j

- openapi-operation-adapters/openapi-operation-vertx/README.md
- openapi-operation-adapters/openapi-operation-vertx/build.gradle
- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/OAI3PathConverter.java
- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/OpenApi3RouterFactoryImpl.java
- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/OperationValidationHandler.java
- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/RequestParameters.java
- openapi-operation-adapters/openapi-operation-vertx/src/test/java/OpenApi3RouterFactoryTest.java
- openapi-operation-adapters/openapi-operation-vertx/src/test/java/VertxTestBase.java
- openapi-operation-adapters/openapi-operation-vertx/src/test/resources/api.yaml
- openapi-operation-adapters/openapi-operation-vertx/src/test/resources/apiOAuthSecured.yaml
- openapi-operation-adapters/openapi-operation-vertx/src/test/resources/apiSecured.yaml
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/RequestParameters.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/RequestValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/OpenApi3.java
> Add Vert.x router factory

- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/OpenApi3RouterFactoryImpl.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/RequestValidator.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/OpenApi4j.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/SchemaPerfRunner.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/SchemaValidator.java
> Operation validator - Enable validation context overrides

- openapi-core/src/main/java/org/openapi4j/core/util/IOUtil.java
- openapi-core/src/main/java/org/openapi4j/core/util/TreeUtil.java
- openapi-core/src/main/java/org/openapi4j/core/validation/ValidationException.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/Body.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/BodyConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/ContentType.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/FormUrlConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/MultipartConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/TypeConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/XmlConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/DelimitedStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FlatStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FormStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/MatrixStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/ParameterConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/StyleConverter.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/model/impl/DefaultRequestTest.java
- openapi-operation-validator/src/test/resources/operation/api.yaml
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Schema.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/bind/SchemaSerializer.java
> Add multipart with complex values

- openapi-perf-checker/README.md
- openapi-perf-checker/build.gradle
- openapi-perf-checker/src/main/java/org/perf/check/GlobalRunner.java
- openapi-perf-checker/src/main/java/org/perf/check/operation/OpenApi4j.java
- openapi-perf-checker/src/main/java/org/perf/check/operation/OperationPerfRunner.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/JsonTools.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/Justify.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/Networknt.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/SchemaPerfRunner.java
- openapi-perf-checker/src/main/resources/operation/api.yaml
Add Justify for schema validation.
Operation validator checks are now per content types.
Some project QoS changes for easier maintenance & reports.
> Perf checker - Complete implementation

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/Response.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/DefaultResponse.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/DeepObjectStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/DelimitedStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FlatStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FormStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/LabelStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/MatrixStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/ParameterConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/SimpleStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/StyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/RequestValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/ResponseValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/model/impl/DefaultRequestTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/parameter/HeaderParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/resources/operation/api.yaml
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/AbsParameter.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Header.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Parameter.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/HeaderValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ParameterValidator.java
> Operation validator - Add response validator

- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/OpenApi3RouterFactoryImpl.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/PathConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/DeepObjectStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FormStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/LabelStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/MatrixStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/ParameterConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/SimpleStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/StyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/BodyValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/ParameterValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/parameter/CookieParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/parameter/HeaderParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/parameter/PathParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/parameter/QueryParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- settings.gradle
Should close #6 
Improve performance also.
> Operation validator - Fix missing checks on malformed content

- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Schema.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/bind/SchemaDeserializer.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/bind/SchemaSerializer.java
- openapi-parser/src/test/resources/validation/v3/schema/valid/schemaType.yaml
> fix : enums MAY be of any type

- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Schema.java
- openapi-parser/src/test/resources/validation/v3/additional-properties/valid/additional-properties.yaml
> fix : additionalProperties serialization

- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/OpenApi3.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/OpenApiValidator.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/SecurityTest.java
- openapi-parser/src/test/resources/validation/v3/security/valid/security-root.yaml
> fix : OpenAPI object mapping on security field

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/DeepObjectStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/DelimitedStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FlatStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/FormStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/LabelStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/MatrixStyleConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/ParameterConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/parameter/StyleConverter.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/CookieParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/HeaderParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/QueryParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
- openapi-operation-validator/src/test/resources/operation/parameter/cookieParameters.yaml
> fix : improve detection consistency of missing parameter vs. null value

- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/Regexes.java
- openapi-parser/src/test/resources/model/v3/oai-integration/fullOfKeywords.yaml
> fix : allow status code ranges in responses

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/Regexes.java
- openapi-parser/src/test/resources/model/v3/oai-integration/fullOfKeywords.yaml
> feat : support status code ranges for response description

- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Schema.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/SchemaValidator.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/DiscriminatorTest.java
- openapi-parser/src/test/resources/validation/v3/discriminator/valid/recursiveDiscriminator.yaml
> fix: discriminator recursive look up

- openapi-parser/src/main/java/org/openapi4j/parser/validation/ValidatorBase.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ContactValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ExternalDocsValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/InfoValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/LicenseValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/OAuthFlowValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/PathValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/SchemaValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/SecuritySchemeValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ServerValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/XmlValidator.java
- openapi-parser/src/test/resources/validation/v3/server/invalid/server.yaml
- openapi-parser/src/test/resources/validation/v3/server/valid/server.yaml
> fix: allow server relative URL (for whatever it means...)

- openapi-core/src/main/resources/META-INF/native-image/reflect-config.json
- openapi-parser/src/main/resources/META-INF/native-image/reflect-config.json
- openapi-perf-checker/build.gradle
- openapi-perf-checker/src/main/java/org/perf/check/operation/OpenApi4j.java
- openapi-perf-checker/src/main/java/org/perf/check/operation/OperationPerfRunner.java
- openapi-perf-checker/src/main/java/org/perf/check/parser/OpenApi4j.java
- openapi-perf-checker/src/main/java/org/perf/check/parser/ParserPerfRunner.java
- openapi-perf-checker/src/main/java/org/perf/check/schema/SchemaPerfRunner.java
- openapi-perf-checker/src/main/resources/META-INF/native-image/resource-config.json
> feat: Add graal config files to allow native compilation.

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/MediaTypeContainer.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/ContentType.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/model/impl/MediaTypeContainerTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
> fix: Improve handling of media type variance.

- openapi-operation-adapters/openapi-operation-vertx/src/main/java/org/openapi4j/operation/validator/adapters/server/vertx/v3/impl/OpenApi3RouterFactoryImpl.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/PathResolver.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/RequestValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationContentTypeTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/RequestValidatorTest.java
- openapi-operation-validator/src/test/resources/request/requestValidator-with-servers.yaml
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Path.java
> Operation validator: add request validation from URL only

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/Body.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/TypeConverter.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/CookieParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/HeaderParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/ParamChecker.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/QueryParamConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/converter/TypeConverterTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
> Improve conversions

- openapi-parser/src/main/java/org/openapi4j/parser/validation/ValidatorBase.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ContactValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ExternalDocsValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/InfoValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/LicenseValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/OAuthFlowValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/SecuritySchemeValidator.java
> fix: relative URL checks are now skipped

- openapi-parser/src/main/java/org/openapi4j/parser/validation/ValidatorBase.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ContactValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ExternalDocsValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/InfoValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/LicenseValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/OAuthFlowValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/SecuritySchemeValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ServerValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/Validator3Base.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/XmlValidator.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/CommonValidationTest.java
- openapi-parser/src/test/resources/model/v3/oai-integration/uspto.yaml
- openapi-parser/src/test/resources/validation/v3/xml/invalid/xml.yaml
> fix: relative URL checks

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
> fix: don't return error when status code has not been found

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/Body.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/model/impl/BodyTest.java
To resolve https://github.com/openapi4j/openapi4j/issues/86
> Use Body.from(Object) instead of Body.from(Map<String,Object>)

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/BodyValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/ParameterValidator.java
> fix: some canonical $ref fields (abs$ref) may be lost

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/BodyValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/OperationValidatorTest.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
- openapi-operation-validator/src/test/resources/operation/operationValidator_refs.yaml
- openapi-parser/README.md
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/AllOfValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/AnyOfValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/DiscriminatorValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/OneOfValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/ReferenceValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/SchemaValidator.java
- openapi-schema-validator/src/test/resources/schema/allOf.json
- openapi-schema-validator/src/test/resources/schema/anyOf.json
- openapi-schema-validator/src/test/resources/schema/discriminator.json
- openapi-schema-validator/src/test/resources/schema/oneOf.json
> fix: discriminator with external references

- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/SchemaValidator.java
- openapi-schema-validator/src/test/resources/schema/nullable.json
> fix: Don't apply additional validators when schema is JSON-Reference

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/convert/MultipartConverter.java
- openapi-operation-validator/src/test/resources/operation/contentType/multipart.json
> feat: accurate conversion for multipart

- openapi-core/src/main/java/org/openapi4j/core/validation/ValidationResults.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/ItemsValidator.java
- openapi-schema-validator/src/test/java/org/openapi4j/schema/validator/ValidationTest.java
- openapi-schema-validator/src/test/resources/schema/items.json
> feat: add array index in crumbs

- openapi-core/src/main/java/org/openapi4j/core/validation/ValidationException.java
- openapi-core/src/main/java/org/openapi4j/core/validation/ValidationResults.java
- openapi-core/src/test/java/org/openapi4j/core/validation/ValidationExceptionTest.java
- openapi-parser/src/test/java/org/openapi4j/parser/Checker.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/ValidationData.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/AdditionalPropertiesValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/AllOfValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/AnyOfValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/ItemsValidator.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/OneOfValidator.java
> fix: report only errors on anyOf/oneOf/allOf on selection/validation failure

- docs/schema-validator.md
- openapi-core/src/main/java/org/openapi4j/core/model/v3/OAI3SchemaKeywords.java
- openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/FormatValidator.java
- openapi-schema-validator/src/test/resources/schema/format.json
> feat: add 'uuid' format

- openapi-operation-adapters/openapi-operation-vertx/src/test/java/OpenApi3RouterFactoryTest.java
- openapi-operation-adapters/openapi-operation-vertx/src/test/java/VertxTestBase.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/model/impl/MediaTypeContainer.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/operation/ResponseTest.java
- openapi-operation-validator/src/test/resources/operation/response_without_content.yaml
> fix: allow no content-type in response

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Operation.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Path.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ExpressionValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/OpenApiValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/PathValidator.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/PathTest.java
- openapi-parser/src/test/resources/validation/v3/path/valid/path_param.yaml
> fix: path param checks

- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ContactValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ExternalDocsValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/InfoValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/LicenseValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/OAuthFlowValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/SecuritySchemeValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ServerValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/Validator3Base.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/ContactTest.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/ServerTest.java
- openapi-parser/src/test/resources/validation/v3/contact/invalid/contact.yaml
- openapi-parser/src/test/resources/validation/v3/contact/invalid/contact_wrong_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/invalid/contact_relative_to_abs_server_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/invalid/contact_relative_to_relative_server_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/invalid/contact_wrong_relative_to_relative_server_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/invalid/server_no_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/invalid/server_wrong_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/valid/contact_relative_to_abs_server_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/valid/contact_relative_to_relative_server_url.yaml
- openapi-parser/src/test/resources/validation/v3/server/valid/server_relative_url.yaml
> fix: check URLs with context base URL

- openapi-operation-adapters/openapi-operation-vertx/src/test/java/OpenApi3RouterFactoryTest.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/BodyValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
> fix: request body not required is still required

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/PathResolver.java
- openapi-parser/src/main/java/org/openapi4j/parser/model/v3/Server.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/ServerValidator.java
- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/Validator3Base.java
- openapi-parser/src/test/resources/validation/v3/server/valid/contact_relative_to_relative_server_url.yaml
> Fix server url template

- build.gradle
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/convert/MultipartConverter.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/convert/TypeConverter.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/convert/TypeConverterTest.java
- openapi-operation-validator/src/test/resources/operation/contentType/contentType.yaml
- openapi-operation-validator/src/test/resources/operation/contentType/multipart.json
> fix: NPE when there's no schema available in multipart converter

- openapi-parser/src/main/java/org/openapi4j/parser/validation/v3/PathValidator.java
- openapi-parser/src/test/java/org/openapi4j/parser/validation/v3/PathTest.java
- openapi-parser/src/test/resources/validation/v3/path/valid/path_param.yaml
> fix: references for path params

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/convert/style/FormStyleConverter.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/operation/QueryTest.java
- openapi-operation-validator/src/test/resources/operation/operationValidator.yaml
> fix: NPE when validating a null query parameter

- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java
- openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/RequestValidator.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/RequestValidatorTest.java
- openapi-operation-validator/src/test/java/org/openapi4j/operation/validator/validation/operation/ResponseTest.java
> add convenience methods to support easy response validation
